#!/usr/bin/env python3
import sys
import helpers
from termcolor import colored
from analyzer import Analyzer

def main():
    
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweet username")
        
    tweets = helpers.get_user_timeline(sys.argv[1], count=50)
    
    analyzer = Analyzer()
    
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{}".format(tweet), "green"))
        elif score < 0.0:
            print(colored("{}".format(tweet), "red"))
        else:
            print(colored("{}".format(tweet), "yellow"))

if __name__ == "__main__":
    main()
    
    


    
    
